name: Docker Image Build With Push
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d_%H%M')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            sotaneum/schedule-job-server:${{ env.DATE }}
            sotaneum/schedule-job-server:latest
          platforms: |
            linux/amd64
            linux/arm64
